package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Marker comments around generated text. A page the generator owns is
// generated whole; on an authored page only the text between the markers is
// replaced.
const (
	beginMarker = "<!-- BEGIN GENERATED by tools/refgen. Do not edit between these markers: run task generate:reference. -->"
	endMarker   = "<!-- END GENERATED by tools/refgen -->"
)

// repoBlobURL is where a `docs/<note>.md` pointer in a doc comment links to.
const repoBlobURL = "https://github.com/open-platform-model/catalog_opm/blob/main/"

// mdEscaper escapes the characters Markdown or the site would read as
// markup in prose taken from CUE: the site renders raw HTML, so `<name>`
// would vanish, and `{{<` would open a Hugo shortcode.
var mdEscaper = strings.NewReplacer(
	`\`, `\\`, `<`, `\<`, `>`, `\>`, `*`, `\*`, `_`, `\_`,
	`[`, `\[`, `]`, `\]`, `|`, `\|`, "{{", `{\{`,
)

// mdText escapes prose for Markdown, leaving `code spans` as written.
func mdText(s string) string {
	var b strings.Builder
	for i, part := range strings.Split(s, "`") {
		if i%2 == 1 {
			b.WriteString("`" + part + "`")
			continue
		}
		b.WriteString(mdEscaper.Replace(part))
	}
	// An unpaired backtick leaves the last part inside an open span; close
	// nothing, the text is as authored.
	return b.String()
}

// cell prepares text for a table cell: a pipe ends the cell even inside a
// code span, so every pipe is escaped.
func cell(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}

// code wraps s in a code span long enough to hold any backticks in it.
func code(s string) string {
	fence := "`"
	for strings.Contains(s, fence) {
		fence += "`"
	}
	if strings.HasPrefix(s, "`") || strings.HasSuffix(s, "`") {
		return fence + " " + s + " " + fence
	}
	return fence + s + fence
}

// yamlString quotes a front-matter value as a YAML double-quoted scalar.
func yamlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

var docNote = regexp.MustCompile(`\bdocs/[a-z0-9-]+\.md\b`)

// notesMarkdown turns doc-comment paragraphs into Markdown paragraphs: the
// lines of a paragraph join with spaces, prose is escaped, and a
// `docs/<note>.md` pointer that exists in the repository becomes a link.
func notesMarkdown(root string, paras []string) string {
	var out []string
	for _, p := range paras {
		text := mdText(strings.Join(strings.Fields(p), " "))
		text = linkDocNotes(root, text)
		out = append(out, text)
	}
	return strings.Join(out, "\n\n")
}

// linkDocNotes links each repository note named outside a code span. The
// name is matched after escaping, so its underscores never appear (note
// names are kebab-case).
func linkDocNotes(root, s string) string {
	parts := strings.Split(s, "`")
	for i := 0; i < len(parts); i += 2 {
		parts[i] = docNote.ReplaceAllStringFunc(parts[i], func(n string) string {
			if _, err := os.Stat(filepath.Join(root, n)); err != nil {
				return n
			}
			return fmt.Sprintf("[%s](%s%s)", n, repoBlobURL, n)
		})
	}
	return strings.Join(parts, "`")
}

// splitDoc checks that a doc comment opens with the description and a
// period, and returns the remaining paragraphs.
func splitDoc(doc, desc string) ([]string, error) {
	if doc == "" {
		return nil, fmt.Errorf("no doc comment: it must open with the description %q", desc+".")
	}
	paras := splitParagraphs(doc)
	first := strings.Join(strings.Fields(paras[0]), " ")
	want := strings.Join(strings.Fields(desc), " ") + "."
	if !strings.HasPrefix(first, want) {
		return nil, fmt.Errorf("doc comment must open with the description %q, but opens %q", want, truncate(first, len(want)+20))
	}
	rest := strings.TrimSpace(first[len(want):])
	var out []string
	if rest != "" {
		out = append(out, rest)
	}
	return append(out, paras[1:]...), nil
}

func splitParagraphs(s string) []string {
	var out []string
	for _, p := range regexp.MustCompile(`\n[ \t]*\n`).Split(strings.TrimSpace(s), -1) {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
