package main

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"cuelang.org/go/cue/format"
)

// entry is one row of the table: a kind with its schema, its scope, or both.
type entry struct {
	apiVersion, kind string
	schema           *def   // nil: the spec serves the kind, x/k8s.io has no definition
	scope            string // "": x/k8s.io defines the kind, the spec does not serve it
}

func (e entry) key() string { return e.apiVersion + " " + e.kind }

// join returns the union of the definitions and the scopes, sorted by
// apiVersion then kind.
func join(defs map[gvk]def, scope map[gvk]string) []entry {
	rows := map[gvk]*entry{}
	for k, d := range defs {
		rows[k] = &entry{apiVersion: k.apiVersion, kind: k.kind, schema: &d}
	}
	for k, s := range scope {
		if rows[k] == nil {
			rows[k] = &entry{apiVersion: k.apiVersion, kind: k.kind}
		}
		rows[k].scope = s
	}
	out := make([]entry, 0, len(rows))
	for _, e := range rows {
		out = append(out, *e)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].apiVersion != out[j].apiVersion {
			return out[i].apiVersion < out[j].apiVersion
		}
		return out[i].kind < out[j].kind
	})
	return out
}

// alias names the import of an x/k8s.io package by its last two path
// elements: api/apps/v1 is apps_v1, apimachinery/pkg/apis/meta/v1 is meta_v1.
func alias(importPath string) string {
	parent, leaf := path.Split(importPath)
	a := path.Base(parent) + "_" + leaf
	return strings.NewReplacer("-", "_", ".", "_").Replace(a)
}

// render writes table.cue for t, formatted by cue/format.
func render(t []entry, version, tag string) ([]byte, error) {
	imports := map[string]string{} // alias -> import path
	for _, e := range t {
		if e.schema == nil {
			continue
		}
		a := alias(e.schema.importPath)
		if prev, ok := imports[a]; ok && prev != e.schema.importPath {
			return nil, fmt.Errorf("import alias %s names both %s and %s", a, prev, e.schema.importPath)
		}
		imports[a] = e.schema.importPath
	}
	aliases := make([]string, 0, len(imports))
	for a := range imports {
		aliases = append(aliases, a)
	}
	sort.Strings(aliases)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/kindgen (task generate:kinds); DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Inputs: the definitions of %s %s, and the scope each kind\n", strings.SplitN(k8sModule, "@", 2)[0], version)
	fmt.Fprintf(&b, "// is served at in Kubernetes %s api/openapi-spec/swagger.json.\n", tag)
	fmt.Fprintf(&b, "package kinds\n\nimport (\n")
	for _, a := range aliases {
		fmt.Fprintf(&b, "\t%s %s\n", a, strconv.Quote(imports[a]))
	}
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "// Every built-in Kubernetes kind, keyed by apiVersion then kind, with its closed schema and its scope.\n")
	fmt.Fprintf(&b, "// A kind without a schema is served by Kubernetes %s but has no %s definition;\n", tag, strings.SplitN(k8sModule, "@", 2)[0])
	fmt.Fprintf(&b, "// a kind without a scope is defined there but not served as an object.\n")
	fmt.Fprintf(&b, "#Table: {\n")
	cur := ""
	for _, e := range t {
		if e.apiVersion != cur {
			if cur != "" {
				fmt.Fprintf(&b, "\t}\n")
			}
			cur = e.apiVersion
			fmt.Fprintf(&b, "\t%s: {\n", strconv.Quote(cur))
		}
		var fields []string
		if e.schema != nil {
			fields = append(fields, "schema: "+alias(e.schema.importPath)+"."+e.schema.name)
		}
		if e.scope != "" {
			fields = append(fields, "scope: "+strconv.Quote(e.scope))
		}
		fmt.Fprintf(&b, "\t\t%s: {%s}\n", e.kind, strings.Join(fields, ", "))
	}
	if cur != "" {
		fmt.Fprintf(&b, "\t}\n")
	}
	fmt.Fprintf(&b, "}\n")
	return format.Source(b.Bytes())
}
