// Code generated by tools/kindgen (task generate:kinds); DO NOT EDIT.
//
// Inputs: the definitions of cue.dev/x/k8s.io v0.12.0, and the scope each kind
// is served at in Kubernetes v1.36.0 api/openapi-spec/swagger.json.
package kinds

import (
	admissionregistration_v1 "cue.dev/x/k8s.io/api/admissionregistration/v1"
	admissionregistration_v1alpha1 "cue.dev/x/k8s.io/api/admissionregistration/v1alpha1"
	admissionregistration_v1beta1 "cue.dev/x/k8s.io/api/admissionregistration/v1beta1"
	apiextensions_v1 "cue.dev/x/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	apiregistration_v1 "cue.dev/x/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1"
	apiserverinternal_v1alpha1 "cue.dev/x/k8s.io/api/apiserverinternal/v1alpha1"
	apps_v1 "cue.dev/x/k8s.io/api/apps/v1"
	authentication_v1 "cue.dev/x/k8s.io/api/authentication/v1"
	authorization_v1 "cue.dev/x/k8s.io/api/authorization/v1"
	autoscaling_v1 "cue.dev/x/k8s.io/api/autoscaling/v1"
	autoscaling_v2 "cue.dev/x/k8s.io/api/autoscaling/v2"
	batch_v1 "cue.dev/x/k8s.io/api/batch/v1"
	certificates_v1 "cue.dev/x/k8s.io/api/certificates/v1"
	certificates_v1alpha1 "cue.dev/x/k8s.io/api/certificates/v1alpha1"
	certificates_v1beta1 "cue.dev/x/k8s.io/api/certificates/v1beta1"
	coordination_v1 "cue.dev/x/k8s.io/api/coordination/v1"
	coordination_v1alpha2 "cue.dev/x/k8s.io/api/coordination/v1alpha2"
	coordination_v1beta1 "cue.dev/x/k8s.io/api/coordination/v1beta1"
	core_v1 "cue.dev/x/k8s.io/api/core/v1"
	discovery_v1 "cue.dev/x/k8s.io/api/discovery/v1"
	events_v1 "cue.dev/x/k8s.io/api/events/v1"
	flowcontrol_v1 "cue.dev/x/k8s.io/api/flowcontrol/v1"
	meta_v1 "cue.dev/x/k8s.io/apimachinery/pkg/apis/meta/v1"
	networking_v1 "cue.dev/x/k8s.io/api/networking/v1"
	networking_v1beta1 "cue.dev/x/k8s.io/api/networking/v1beta1"
	node_v1 "cue.dev/x/k8s.io/api/node/v1"
	policy_v1 "cue.dev/x/k8s.io/api/policy/v1"
	rbac_v1 "cue.dev/x/k8s.io/api/rbac/v1"
	resource_v1 "cue.dev/x/k8s.io/api/resource/v1"
	resource_v1alpha3 "cue.dev/x/k8s.io/api/resource/v1alpha3"
	resource_v1beta1 "cue.dev/x/k8s.io/api/resource/v1beta1"
	resource_v1beta2 "cue.dev/x/k8s.io/api/resource/v1beta2"
	scheduling_v1 "cue.dev/x/k8s.io/api/scheduling/v1"
	scheduling_v1alpha2 "cue.dev/x/k8s.io/api/scheduling/v1alpha2"
	storage_v1 "cue.dev/x/k8s.io/api/storage/v1"
	storage_v1beta1 "cue.dev/x/k8s.io/api/storage/v1beta1"
	storagemigration_v1beta1 "cue.dev/x/k8s.io/api/storagemigration/v1beta1"
)

// Every built-in Kubernetes kind, keyed by apiVersion then kind, with its closed schema and its scope.
// A kind without a schema is served by Kubernetes v1.36.0 but has no cue.dev/x/k8s.io definition;
// a kind without a scope is defined there but not served as an object.
#Table: {
	"admissionregistration.k8s.io/v1": {
		MutatingAdmissionPolicy: {schema: admissionregistration_v1.#MutatingAdmissionPolicy, scope: "Cluster"}
		MutatingAdmissionPolicyBinding: {schema: admissionregistration_v1.#MutatingAdmissionPolicyBinding, scope: "Cluster"}
		MutatingWebhookConfiguration: {schema: admissionregistration_v1.#MutatingWebhookConfiguration, scope: "Cluster"}
		ValidatingAdmissionPolicy: {schema: admissionregistration_v1.#ValidatingAdmissionPolicy, scope: "Cluster"}
		ValidatingAdmissionPolicyBinding: {schema: admissionregistration_v1.#ValidatingAdmissionPolicyBinding, scope: "Cluster"}
		ValidatingWebhookConfiguration: {schema: admissionregistration_v1.#ValidatingWebhookConfiguration, scope: "Cluster"}
	}
	"admissionregistration.k8s.io/v1alpha1": {
		MutatingAdmissionPolicy: {schema: admissionregistration_v1alpha1.#MutatingAdmissionPolicy, scope: "Cluster"}
		MutatingAdmissionPolicyBinding: {schema: admissionregistration_v1alpha1.#MutatingAdmissionPolicyBinding, scope: "Cluster"}
	}
	"admissionregistration.k8s.io/v1beta1": {
		MutatingAdmissionPolicy: {schema: admissionregistration_v1beta1.#MutatingAdmissionPolicy, scope: "Cluster"}
		MutatingAdmissionPolicyBinding: {schema: admissionregistration_v1beta1.#MutatingAdmissionPolicyBinding, scope: "Cluster"}
	}
	"apiextensions.k8s.io/v1": {
		CustomResourceDefinition: {schema: apiextensions_v1.#CustomResourceDefinition, scope: "Cluster"}
	}
	"apiregistration.k8s.io/v1": {
		APIService: {schema: apiregistration_v1.#APIService, scope: "Cluster"}
	}
	"apps/v1": {
		ControllerRevision: {schema: apps_v1.#ControllerRevision, scope: "Namespaced"}
		DaemonSet: {schema: apps_v1.#DaemonSet, scope: "Namespaced"}
		Deployment: {schema: apps_v1.#Deployment, scope: "Namespaced"}
		ReplicaSet: {schema: apps_v1.#ReplicaSet, scope: "Namespaced"}
		StatefulSet: {schema: apps_v1.#StatefulSet, scope: "Namespaced"}
	}
	"authentication.k8s.io/v1": {
		SelfSubjectReview: {schema: authentication_v1.#SelfSubjectReview, scope: "Cluster"}
		TokenRequest: {schema: authentication_v1.#TokenRequest, scope: "Namespaced"}
		TokenReview: {schema: authentication_v1.#TokenReview, scope: "Cluster"}
	}
	"authorization.k8s.io/v1": {
		LocalSubjectAccessReview: {schema: authorization_v1.#LocalSubjectAccessReview, scope: "Namespaced"}
		SelfSubjectAccessReview: {schema: authorization_v1.#SelfSubjectAccessReview, scope: "Cluster"}
		SelfSubjectRulesReview: {schema: authorization_v1.#SelfSubjectRulesReview, scope: "Cluster"}
		SubjectAccessReview: {schema: authorization_v1.#SubjectAccessReview, scope: "Cluster"}
	}
	"autoscaling/v1": {
		HorizontalPodAutoscaler: {schema: autoscaling_v1.#HorizontalPodAutoscaler, scope: "Namespaced"}
		Scale: {schema: autoscaling_v1.#Scale}
	}
	"autoscaling/v2": {
		HorizontalPodAutoscaler: {schema: autoscaling_v2.#HorizontalPodAutoscaler, scope: "Namespaced"}
	}
	"batch/v1": {
		CronJob: {schema: batch_v1.#CronJob, scope: "Namespaced"}
		Job: {schema: batch_v1.#Job, scope: "Namespaced"}
	}
	"certificates.k8s.io/v1": {
		CertificateSigningRequest: {schema: certificates_v1.#CertificateSigningRequest, scope: "Cluster"}
	}
	"certificates.k8s.io/v1alpha1": {
		ClusterTrustBundle: {schema: certificates_v1alpha1.#ClusterTrustBundle, scope: "Cluster"}
	}
	"certificates.k8s.io/v1beta1": {
		ClusterTrustBundle: {schema: certificates_v1beta1.#ClusterTrustBundle, scope: "Cluster"}
		PodCertificateRequest: {schema: certificates_v1beta1.#PodCertificateRequest, scope: "Namespaced"}
	}
	"coordination.k8s.io/v1": {
		Lease: {schema: coordination_v1.#Lease, scope: "Namespaced"}
	}
	"coordination.k8s.io/v1alpha2": {
		LeaseCandidate: {schema: coordination_v1alpha2.#LeaseCandidate, scope: "Namespaced"}
	}
	"coordination.k8s.io/v1beta1": {
		LeaseCandidate: {schema: coordination_v1beta1.#LeaseCandidate, scope: "Namespaced"}
	}
	"discovery.k8s.io/v1": {
		EndpointSlice: {schema: discovery_v1.#EndpointSlice, scope: "Namespaced"}
	}
	"events.k8s.io/v1": {
		Event: {schema: events_v1.#Event, scope: "Namespaced"}
	}
	"flowcontrol.apiserver.k8s.io/v1": {
		FlowSchema: {schema: flowcontrol_v1.#FlowSchema, scope: "Cluster"}
		PriorityLevelConfiguration: {schema: flowcontrol_v1.#PriorityLevelConfiguration, scope: "Cluster"}
	}
	"internal.apiserver.k8s.io/v1alpha1": {
		StorageVersion: {schema: apiserverinternal_v1alpha1.#StorageVersion, scope: "Cluster"}
	}
	"networking.k8s.io/v1": {
		IPAddress: {schema: networking_v1.#IPAddress, scope: "Cluster"}
		Ingress: {schema: networking_v1.#Ingress, scope: "Namespaced"}
		IngressClass: {schema: networking_v1.#IngressClass, scope: "Cluster"}
		NetworkPolicy: {schema: networking_v1.#NetworkPolicy, scope: "Namespaced"}
		ServiceCIDR: {schema: networking_v1.#ServiceCIDR, scope: "Cluster"}
	}
	"networking.k8s.io/v1beta1": {
		IPAddress: {schema: networking_v1beta1.#IPAddress, scope: "Cluster"}
		ServiceCIDR: {schema: networking_v1beta1.#ServiceCIDR, scope: "Cluster"}
	}
	"node.k8s.io/v1": {
		RuntimeClass: {schema: node_v1.#RuntimeClass, scope: "Cluster"}
	}
	"policy/v1": {
		Eviction: {schema: policy_v1.#Eviction, scope: "Namespaced"}
		PodDisruptionBudget: {schema: policy_v1.#PodDisruptionBudget, scope: "Namespaced"}
	}
	"rbac.authorization.k8s.io/v1": {
		ClusterRole: {schema: rbac_v1.#ClusterRole, scope: "Cluster"}
		ClusterRoleBinding: {schema: rbac_v1.#ClusterRoleBinding, scope: "Cluster"}
		Role: {schema: rbac_v1.#Role, scope: "Namespaced"}
		RoleBinding: {schema: rbac_v1.#RoleBinding, scope: "Namespaced"}
	}
	"resource.k8s.io/v1": {
		DeviceClass: {schema: resource_v1.#DeviceClass, scope: "Cluster"}
		ResourceClaim: {schema: resource_v1.#ResourceClaim, scope: "Namespaced"}
		ResourceClaimTemplate: {schema: resource_v1.#ResourceClaimTemplate, scope: "Namespaced"}
		ResourceSlice: {schema: resource_v1.#ResourceSlice, scope: "Cluster"}
	}
	"resource.k8s.io/v1alpha3": {
		DeviceTaintRule: {schema: resource_v1alpha3.#DeviceTaintRule, scope: "Cluster"}
		ResourcePoolStatusRequest: {schema: resource_v1alpha3.#ResourcePoolStatusRequest, scope: "Cluster"}
	}
	"resource.k8s.io/v1beta1": {
		DeviceClass: {schema: resource_v1beta1.#DeviceClass, scope: "Cluster"}
		ResourceClaim: {schema: resource_v1beta1.#ResourceClaim, scope: "Namespaced"}
		ResourceClaimTemplate: {schema: resource_v1beta1.#ResourceClaimTemplate, scope: "Namespaced"}
		ResourceSlice: {schema: resource_v1beta1.#ResourceSlice, scope: "Cluster"}
	}
	"resource.k8s.io/v1beta2": {
		DeviceClass: {schema: resource_v1beta2.#DeviceClass, scope: "Cluster"}
		DeviceTaintRule: {schema: resource_v1beta2.#DeviceTaintRule, scope: "Cluster"}
		ResourceClaim: {schema: resource_v1beta2.#ResourceClaim, scope: "Namespaced"}
		ResourceClaimTemplate: {schema: resource_v1beta2.#ResourceClaimTemplate, scope: "Namespaced"}
		ResourceSlice: {schema: resource_v1beta2.#ResourceSlice, scope: "Cluster"}
	}
	"scheduling.k8s.io/v1": {
		PriorityClass: {schema: scheduling_v1.#PriorityClass, scope: "Cluster"}
	}
	"scheduling.k8s.io/v1alpha2": {
		PodGroup: {schema: scheduling_v1alpha2.#PodGroup, scope: "Namespaced"}
		Workload: {schema: scheduling_v1alpha2.#Workload, scope: "Namespaced"}
	}
	"storage.k8s.io/v1": {
		CSIDriver: {schema: storage_v1.#CSIDriver, scope: "Cluster"}
		CSINode: {schema: storage_v1.#CSINode, scope: "Cluster"}
		CSIStorageCapacity: {schema: storage_v1.#CSIStorageCapacity, scope: "Namespaced"}
		StorageClass: {schema: storage_v1.#StorageClass, scope: "Cluster"}
		VolumeAttachment: {schema: storage_v1.#VolumeAttachment, scope: "Cluster"}
		VolumeAttributesClass: {schema: storage_v1.#VolumeAttributesClass, scope: "Cluster"}
	}
	"storage.k8s.io/v1beta1": {
		VolumeAttributesClass: {schema: storage_v1beta1.#VolumeAttributesClass, scope: "Cluster"}
	}
	"storagemigration.k8s.io/v1beta1": {
		StorageVersionMigration: {schema: storagemigration_v1beta1.#StorageVersionMigration, scope: "Cluster"}
	}
	"v1": {
		APIGroup: {schema: meta_v1.#APIGroup}
		APIVersions: {schema: meta_v1.#APIVersions}
		Binding: {schema: core_v1.#Binding, scope: "Namespaced"}
		ComponentStatus: {schema: core_v1.#ComponentStatus, scope: "Cluster"}
		ConfigMap: {schema: core_v1.#ConfigMap, scope: "Namespaced"}
		Endpoints: {schema: core_v1.#Endpoints, scope: "Namespaced"}
		Event: {schema: core_v1.#Event, scope: "Namespaced"}
		LimitRange: {schema: core_v1.#LimitRange, scope: "Namespaced"}
		Namespace: {schema: core_v1.#Namespace, scope: "Cluster"}
		Node: {schema: core_v1.#Node, scope: "Cluster"}
		PersistentVolume: {schema: core_v1.#PersistentVolume, scope: "Cluster"}
		PersistentVolumeClaim: {schema: core_v1.#PersistentVolumeClaim, scope: "Namespaced"}
		Pod: {schema: core_v1.#Pod, scope: "Namespaced"}
		PodTemplate: {schema: core_v1.#PodTemplate, scope: "Namespaced"}
		ReplicationController: {schema: core_v1.#ReplicationController, scope: "Namespaced"}
		ResourceQuota: {schema: core_v1.#ResourceQuota, scope: "Namespaced"}
		Secret: {schema: core_v1.#Secret, scope: "Namespaced"}
		Service: {schema: core_v1.#Service, scope: "Namespaced"}
		ServiceAccount: {schema: core_v1.#ServiceAccount, scope: "Namespaced"}
		Status: {schema: meta_v1.#Status}
	}
}
